version: "3"

services:
  exporter:
    build: .
    command: python -m dramatiq iris_exporter.exporter
    volumes:
      - ./iris_exporter:/app/iris_exporter:ro

  watcher:
    build: .
    command: python -m iris_exporter.watcher
    environment:
      OAUTHLIB_INSECURE_TRANSPORT: 1
    volumes:
      - ./iris_exporter:/app/iris_exporter:ro
