[tool.poetry]
name = "iris-exporter"
version = "0.1.0"
description = "Export Iris measurements in multiple formats."
authors = ["Maxime Mouchet <maxime.mouchet@lip6.fr>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.21.0"
diamond-miner = "^0.7.4"
dioptra-iris-client = "^0.4.0"
dioptra-pych = {extras = ["orjson"], version = "^0.1.2"}
dramatiq = {extras = ["redis", "watch"], version = "^1.12.2"}
httpx = "^0.22.0"
pydantic = "^1.9.0"
redis = "^4.1.4"

[tool.poetry.dev-dependencies]
boto3-stubs = {extras = ["s3"], version = "^1.21.0"}
mypy = "^0.931"
pre-commit = "^2.17.0"
pytest = "^7.0.1"
pytest-asyncio = "^0.18.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
